export enum ErrorStatus {
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
